application.name: demo-api

application.main_service.port: 8888
application.monitoring_service.port: 8889

mysql.host: 127.0.0.1
mysql.port: 3306
mysql.db: online_voting
mysql.user: root
mysql.password: root
mysql.pool_size: 10